# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.24.0
# source: host.sql
import dataclasses
from typing import Any, Optional

import sqlalchemy

from sqlc import models


CREATE_HOST = """-- name: create_host \\:execresult
INSERT INTO host (
    owner_id,
    title,
    description,
    type,
    location,
    facilities,
    price
) VALUES (
    :p1, :p2, :p3, :p4, :p5, :p6, :p7
)
"""


@dataclasses.dataclass()
class CreateHostParams:
    owner_id: Optional[Any]
    title: Any
    description: Any
    type: Any
    location: Any
    facilities: Any
    price: Any


DELETE_HOST = """-- name: delete_host \\:execresult
DELETE from host WHERE id = :p1
"""


GET_HOST = """-- name: get_host \\:one
SELECT id, owner_id, title, description, type, location, facilities, price FROM host WHERE id = :p1 LIMIT 1
"""


LIST_HOST = """-- name: list_host \\:many
SELECT id, owner_id, title, description, type, location, facilities, price from host
"""


LIST_HOST_BY_OWNER = """-- name: list_host_by_owner \\:many
SELECT id, owner_id, title, description, type, location, facilities, price from host WHERE owner_id = :p1
"""


UPDATE_HOST = """-- name: update_host \\:execresult
UPDATE host
SET 
    title= :p1,
    description= :p2,
    type= :p3,
    location= :p4,
    facilities= :p5,
    price= :p6 
WHERE id= :p7
"""


@dataclasses.dataclass()
class UpdateHostParams:
    title: Any
    description: Any
    type: Any
    location: Any
    facilities: Any
    price: Any
    id: Any


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_host(self, arg: CreateHostParams) -> sqlalchemy.engine.Result:
        return self._conn.execute(sqlalchemy.text(CREATE_HOST), {
            "p1": arg.owner_id,
            "p2": arg.title,
            "p3": arg.description,
            "p4": arg.type,
            "p5": arg.location,
            "p6": arg.facilities,
            "p7": arg.price,
        })

    def delete_host(self, *, id: Any) -> sqlalchemy.engine.Result:
        return self._conn.execute(sqlalchemy.text(DELETE_HOST), {"p1": id})

    def get_host(self, *, id: Any) -> sqlalchemy.engine.Result:
        return self._conn.execute(sqlalchemy.text(GET_HOST), {"p1": id})

    def list_host(self) -> sqlalchemy.engine.Result:
        return self._conn.execute(sqlalchemy.text(LIST_HOST))

    def list_host_by_owner(self, *, owner_id: Optional[Any]) -> sqlalchemy.engine.Result:
        return self._conn.execute(sqlalchemy.text(LIST_HOST_BY_OWNER), {"p1": owner_id})

    def update_host(self, arg: UpdateHostParams) -> sqlalchemy.engine.Result:
        return self._conn.execute(sqlalchemy.text(UPDATE_HOST), {
            "p1": arg.title,
            "p2": arg.description,
            "p3": arg.type,
            "p4": arg.location,
            "p5": arg.facilities,
            "p6": arg.price,
            "p7": arg.id,
        })
