# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.24.0
import dataclasses
from typing import Any, Optional


@dataclasses.dataclass()
class Account:
    id: Any
    full_name: Any
    email: Any
    password: Any


@dataclasses.dataclass()
class Host:
    id: Any
    owner_id: Optional[Any]
    title: Any
    description: Any
    type: Any
    location: Any
    facilities: Any
    price: Any


@dataclasses.dataclass()
class Image:
    id: Any
    host_id: Optional[Any]
    image_bytes: Any


@dataclasses.dataclass()
class Pp:
    id: Any
    account_id: Optional[Any]
    image_bytes: Any


@dataclasses.dataclass()
class Review:
    id: Any
    ticket_id: Optional[Any]
    writer_id: Optional[Any]
    host_id: Optional[Any]
    writer_name: Any
    comment: Any
    created_at: Any


@dataclasses.dataclass()
class Ticket:
    id: Any
    holder_id: Optional[Any]
    host_id: Optional[Any]
    valid_at: Any
    expired_at: Any
    is_finish: Any
    price: Any
