# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.24.0
# source: pp.sql
import dataclasses
from typing import Any, Optional

import sqlalchemy

from sqlc import models


CREATE_PP = """-- name: create_pp \\:execresult
INSERT INTO pp (
    account_id,
    image_bytes
) VALUES (
    :p1, :p2
)
"""


@dataclasses.dataclass()
class CreatePPParams:
    account_id: Optional[Any]
    image_bytes: Any


DELETE_PP = """-- name: delete_pp \\:execresult
DELETE FROM pp WHERE account_id = :p1
"""


GET_PP = """-- name: get_pp \\:one
SELECT id, account_id, image_bytes FROM pp WHERE account_id = :p1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_pp(self, arg: CreatePPParams) -> sqlalchemy.engine.Result:
        return self._conn.execute(sqlalchemy.text(CREATE_PP), {"p1": arg.account_id, "p2": arg.image_bytes})

    def delete_pp(self, *, account_id: Optional[Any]) -> sqlalchemy.engine.Result:
        return self._conn.execute(sqlalchemy.text(DELETE_PP), {"p1": account_id})

    def get_pp(self, *, account_id: Optional[Any]) -> sqlalchemy.engine.Result:
        return self._conn.execute(sqlalchemy.text(GET_PP), {"p1": account_id})
